### ISSUE TITLE
Состояние вкладок в формах

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#20]
После обновления формы вкладка сбрасывается на первую
https://github.com/webadmin87/rzwebsys7/blob/master/common/widgets/admin/views/form.php#L19

можно доработать скрипт и сохранять состояние вкладки после перезагрузки страницы. 
http://stackoverflow.com/questions/10523433/how-do-i-keep-the-current-tab-active-with-twitter-bootstrap-after-a-page-reload

**Comment by webadmin87** [comment]
Исправлено.
