### ISSUE TITLE
Grid for authors

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#22]
Посмотрел код в сценарии search
https://github.com/webadmin87/rzwebsys7/blob/master/common/db/ActiveRecord.php#L251

Можно ли добавить условие для авторов.
andWhere [ 'author_id', Yii::app()->user->id ] 
чтобы в гриде с разрешением авторов (например showOwnItems) показывались только его записи, а для админа выводился весь грид
Как правильно такое реализовать, пока в замешательстве ). 
Или у Вас уже такое реализовано?

**Comment by webadmin87** [comment]
В системе реализована система прав доступ на СRUD операции с моделями. Настройка осуществляется в разделе "Права доступа" главного модуля. Для каждой модели и роли указываются разрешенные операции. При этом можно задать дополнительные ограничения реализовав интерфейс \common\rbac\IConstraint.

Чтобы применить ограничение по автору можно воспользоваться готовой реализацией \app\modules\main\rbac\AuthorConstraint. Соответственно для роли admin класс ограничения не прописывается, а для роли к которой должно быть применено ограничение прописывается указанный класс.

За создание ролей отвечает компонент  "rbacInstaller". По умолчанию это \app\modules\main\rbac\Installer

**Comment by loveorigami** [comment]
Это все верно. Но я имел ввиду такой момент (делал на yii1)
* Есть модуль новостей. В него могут писать много пользователей. Заходим под админом
![01](https://cloud.githubusercontent.com/assets/98164/8157785/797b9536-1368-11e5-92ae-4cd4898c5a21.jpg)
* Есть пользователь (poster), он пишет новости. Заходим в админку под ним.
![02](https://cloud.githubusercontent.com/assets/98164/8157815/b2cb6866-1368-11e5-8d90-1876e3732470.jpg)

Показываются только его записи. 

В модели (Yii1) у меня было так
```php
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('hide',$this->hide,true);
		$criteria->compare('publ_date',$this->publ_date,true);
		$criteria->compare('onmain',$this->onmain,true);
		$criteria->compare('noindex',$this->noindex,true);
		
		if(Yii::app()->user->checkAccess('editor')){ 
// тут у меня проверка прав, является ли пользователь редактором
// если да - выбираем все записи
			$criteria->compare('author_id',$this->author_id,true);
		}
		else{
// если нет - только свои
			$criteria->compare('author_id', Yii::app()->user->id, true);
		}
	 
		
// соответсвенно, и пагинация будет работать, в зависимости от критерия
		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array(
                'pageSize'=>50,
            ),
			'sort' => array (
            'defaultOrder'=>'id DESC'
        )
		));
	}
```

собственно, такую реализацию я пытался найти у Вас.

**Comment by webadmin87** [comment]
Именно это я и имел ввиду. Если в разделе "Права доступа" для какой либо роли и класса прописать AuthorConstraint, то при формировании списка будет вызван метод https://github.com/webadmin87/rzwebsys7/blob/master/app/modules/main/rbac/AuthorConstraint.php#L22
В результате чего пользователь увидит только свои записи.

**Comment by loveorigami** [comment]
спасибо. интересный подход. кажется - то, что нужно.
попробую у себя воспроизвести.

**Comment by loveorigami** [comment]
Я все таки сделал немного проще. 
Может Вам будет интересно...
Сделал иерархию прав.
user->author->editor->admin->root

определил, что минимальная роль, которая может видеть все записи - это editor.
те, что ниже - видят только свои.

добавил сюда
https://github.com/webadmin87/rzwebsys7/blob/master/common/db/ActiveRecord.php#L257
```php
        // если не редактор - показываем записи пользователя
        if(!Yii::$app->user->can('editor')){
            $query->andWhere(["author_id" => Yii::$app->user->id]);
        }
```
и теперь достаются записи только данного пользователя при наличии прав author и user

**Comment by webadmin87** [comment]
Данный подход  удобен при простых ограничениях, как например в Вашем случае - ограничить вывод по автору. Однако в более сложных случая когда для разных моделей и ролей нужны разные ограничения, реализованный в системе подход я считаю более предпочтительным.  
Например, есть риэлторский сайт на котором разные организации размещают свои объявления. Соответственно пользователь с ролью риэлтор должен иметь доступ только к своим объявлениям, не добавленным в архив, а с ролью директор к объявлениям своей организации. Плюс могут быть какие то общедоступные справочники. И т.д. В таком случае чтобы реализовать описанный подход придется переопределять метод search в моделях и делать более сложные проверки.
При существующем подходе ограничения описываются в отдельном классе что более удобно.

Также если Вы решили не использовать существующий подход к разграничению прав необходимо убедится что пользователи с ролью author не могут изменять/удалять чужие объекты по прямым ссылкам.

**Comment by loveorigami** [comment]
Спасибо за разъяснение.
Насчет последнего - это да. там у меня используется rule class (как в доках по Yii2).
Но все равно спасибо за предупреждение.
Проверил - не удаляют ))

**Comment by loveorigami** [comment]
Все таки попытался вникнуть в суть происходящего с AuthorConstraint...

У меня есть модуль новостей.
Хочу сделать, чтобы
author - видел и удалял только свои
editor - мог редактировать все
admin - мог редактировать и удалять все

Создал у вас в админке нового пользователя. Дал ему права admin.
Применил для модели news AuthorConstraint.
Зашел в новости - и вижу только свои записи...
Что в принципе и логично...
=========
UPD:

Я так понял - в самом классе AuthorConstraint нужно еще сделать проверку по роли.
Ту что я предлагал выше...
```php
        // если не редактор - показываем записи пользователя
        if(!Yii::$app->user->can('admin')){
            $query->andWhere(["author_id" => Yii::$app->user->id]);
        }
```
Проверил - действительно так и есть - очень практичное решение!... Спасибо за объяснение.

**Comment by webadmin87** [comment]
На самом деле не совсем так. В AuthorConstraint проверку по роли делать не обязательно. Для этого есть раздел "Права доступа" главного модуля. В данном разделе для модели News создаете три записи - для роли admin, editor и author. Для роли author также прописываете класс AuthorConstraint. Собственно и все.
