### ISSUE TITLE
SluggableBehavior

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#23]
Поставил на локалке Вашу Cms.
Первые впечатления - весьма положительные).
Однако... )))
Не сразу понял, что под "Символьный код" подразумевается alias (или slug).
Для него тоже есть поведение. Не нужно заполнять "ручками". 
http://www.yiiframework.com/doc-2.0/yii-behaviors-sluggablebehavior.html
Но "из коробки" у него есть недостаток - не правильно транслитирует на рус. язык.

Фиксит данный баг поведение от Zelenin
https://github.com/zelenin/yii2-slug-behavior
+ есть возможность создавать составной slug (id-name).

Очень бы хотелось увидеть у Вас эту реализацию.

А также понять, как в стандартные поведения 
https://github.com/webadmin87/rzwebsys7/blob/master/common/db/ActiveRecord.php#L213
добавить свое поведения, в котором присутствует параметр.

на примере SluggableBehavior
```php
// для новостей у меня slug простой (транслит из имени, уникальный)
public function behaviors()
{
    return [
        'slug' => [
            'class' => 'Zelenin\yii\behaviors\Slug',
            'slugAttribute' => 'slug',
            'attribute' => 'name', 
            // optional params
            'ensureUnique' => true,
            'translit' => true,
            'replacement' => '-',
            'lowercase' => true,
            'immutable' => false,
            // If intl extension is enabled, see http://userguide.icu-project.org/transforms/general. 
            'transliterateOptions' => 'Russian-Latin/BGN;'
        ]
    ];
}

// для статей - составной
public function behaviors()
{
    return [
        'slug' => [
            'class' => 'Zelenin\yii\behaviors\Slug',
            'slugAttribute' => 'slug',
            'attribute' => '['id', 'name']', // 1-hello-world
            // optional params
            'ensureUnique' => false,
            'translit' => true,
            'replacement' => '-',
            'lowercase' => true,
            'immutable' => false,
            // If intl extension is enabled, see http://userguide.icu-project.org/transforms/general. 
            'transliterateOptions' => 'Russian-Latin/BGN;'
        ]
    ];
}

```
получается, что из всех настроек в этом поведении некоторые меняются, некоторые нет.
Было бы удобно прописать это поведение с настройками по умолчанию, а в случае необходимости поменять их в конфиге meta-модели 
https://github.com/webadmin87/rzwebsys7/blob/master/app/modules/news/models/meta/NewsMeta.php#L70

**Comment by webadmin87** [comment]
Добавил возможность автогенерации символьного кода с помощью указанного поведения. Есть также возможность переопределять все его параметры.
Чтобы переопределить стандартные поведения или добавить свои можно переопределить метод behaviors.
