### ISSUE TITLE
jQuery bind

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#26]
Тут 
https://github.com/webadmin87/rzwebsys7/blob/7a902a1ea73c3dc94100736034d69f14b94ceb12/app/views/layouts/admin.php#L45
.bind лучше заменить на .on. C версии 1,7 .on предпочтительнее. A .bind будет упразднен.

http://api.jquery.com/on/
https://toster.ru/q/22322

**Comment by webadmin87** [comment]
Согласен, исправлено
