### ISSUE TITLE
Отключение класса ограничения

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#30]
Добавил class AuthorConstraint к модели. Все работает.
Делаю его неактивным - а он все равно применяется.
Ошибка в модели Permissions
https://github.com/webadmin87/rzwebsys7/blob/master/app/modules/main/models/Permission.php#L46
Необходимо метод published() вызвать после where(...)
```php
       if (!isset(self::$_permissions[$class])) {
            self::$_permissions[$class] = static::find()->where(["model" => $class])->published()->one();
        }
```

**Comment by webadmin87** [comment]
Исправил
