### ISSUE TITLE
$editorOptions в HtmlInput для CKEditor

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#33]
Так и не понял, как можно задать опции редактора через meta.

Тут они записаны напрямую 
https://github.com/webadmin87/rzwebsys7/blob/master/common/inputs/HtmlInput.php#L36
и больше не перезаписываются..

например, хочу задать для редактора 
```php
 'preset'=>'standart'
```
вместо full
https://github.com/webadmin87/rzwebsys7/blob/master/common/inputs/HtmlInput.php#L37

как правильнее это сделать?

**Comment by loveorigami** [comment]
В продолжение темы...
У себя хочу использовать PathController.
Подключается он как
```php
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\ElFinder;

$form->field($model, 'attribute')->widget(CKEditor::className(), [
  ...
  'editorOptions' => ElFinder::ckeditorOptions(['elfinder', 'path' => 'some/sub/path'],[/* Some CKEditor Options */]),
  ...
]);
```
тут
https://github.com/webadmin87/rzwebsys7/blob/master/common/inputs/HtmlInput.php#L43
есть свойство fileManagerController.
Можно ли его как то изменить через мета
Например, на "fileManagerController"=>['elfinder', 'path' => 'img'],

Или проще написать свой HtmlInput и нужные свойства устанавливать через options?

**Comment by webadmin87** [comment]
Опции редактора можно задать через свойство widgetOptions класса Field (в конфигурации meta).

По второму вопросу. У класса Field есть свойство inputClass. В него можно передать как строку с именем класса, так и массив с конфигурацией Input класса. Тут можно и переопределить свойство fileManagerController

**Comment by loveorigami** [comment]
Разобрался. Спасибо большое.
