### ISSUE TITLE
Поиск детей в гриде

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#38]
Создал древовидную модель.
Заполнил тестовыми данными.

Нахожусь на главной странице (1 уровень). Элементов очень много... Т.к. детей я не вижу, мне нужно найти, к примеру, элемент из 3 уровня. 

Делаю поиск через расширенный виджет. Но он ищет только по первому уровню...
Даже если зайду внутрь 2 уровня, все равно ищет по первому...

**Comment by webadmin87** [comment]
Исправил, теперь расширенный фильтр будет искать по всей иерархии.

**Comment by loveorigami** [comment]
Спасибо, работает
