### ISSUE TITLE
Жадная загрузка для HasOneField

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#41]
Заметил, что HasOneField (для автора и др. полей) генерирует для каждой строки в гриде отдельный  запрос. И набирается таковых до 100 штук...

Поскольку HasOneField не может быть пустым (по задумке), 
https://github.com/webadmin87/rzwebsys7/blob/master/common/db/MetaFields.php#L198

можно ли, используя relation
https://github.com/webadmin87/rzwebsys7/blob/master/common/db/MetaFields.php#L204

сформировать  "жадную" загрузку данных
подробнее тут - http://www.yiiframework.ru/forum/viewtopic.php?t=22772

т.е для автора добавить `...->with('author')->...`

**Comment by loveorigami** [comment]
Решаю пока "в лоб" ).
В гриде 2 HasOneField - авторы и типы. 20 записей на странице (153 запроса). 
тут добавил
https://github.com/webadmin87/rzwebsys7/blob/master/common/db/ActiveRecord.php#L262
```php
        $query = $query ? $query : static::find()->with('author', 'type');
```
получил 115 запросов.

**Comment by loveorigami** [comment]
не знаю, насколько правильно, но добавил следующий фрагмент там же.
```php
        $query = $query ? $query : static::find();

        foreach ($fields AS $field){
            if(isset($field->relation)){
               $query->with($field->relation);
            }
        }

```
получил желаемый результат

**Comment by webadmin87** [comment]
Сделал для HasOneField параметр eagerLoading. Думаю так будет гибче. Для авторов установил по умолчанию в true.

**Comment by loveorigami** [comment]
Спасибо. работает!
