### ISSUE TITLE
Eav модуль для магазина.

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#48]
Разбираюсь с модулем shop.
Есть необходимость для разных категорий задать доп. аттрибуты.
Например, категория:
* Телевизоры (размер экрана, матрица, частота кадра...)
* Бумага (формат, плотность, цвет...)

Для этих целей есть модуль https://github.com/Mirocow/yii2-eav
Переписал я его с учетом ядра системы с Metа моделями...

Теперь возник вопрос - как его подключить через мета-модель продуктов?
https://github.com/webadmin87/rzwebsys7/blob/master/app/modules/catalog/models/meta/ProducerMeta.php

-------

За вывод eav - полей отвечает следующий код
```php
foreach($model->getEavAttributes()->all() as $attr){
    echo $form->field($model, $attr->name, ['class' => '\mirocow\eav\widgets\ActiveField'])->eavInput();
}        
```
следовательно, нужно создать input-class, типа "class" => \common\db\fields\EavField::className(), в нем подключить поведение...

но как сгенерировать eav поля формы, не пойму.
Ведь для объявления в мета модели input-classa нужен аттрибут. А его на самом деле нет...

Или возможен другой подход для подключения eav модуля?

Прописать в модели продуктов свойств ```isEavModel=true``` ?

**Comment by webadmin87** [comment]
Думаю да, надо создать класс EavField и для него EavInput, в котором уже и генерить eav поля.

**Comment by loveorigami** [comment]
Да, все получилось.
Объявил в модели свойство $eav, затем прописал в мета и подключил EavField с EavInput.
