### ISSUE TITLE
Кеширование с рейтингом

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#54]
Есть вывод записей, аналогичный 
https://github.com/webadmin87/rzwebsys7/blob/master/app/modules/catalog/controllers/CatalogController.php#L100

Под каждой записью выводится виджет рейтинга.

Если страница берется не из кеша, тогда виджет работает корректно.
Однако после перезагрузки рейтинг перестает работать. Т.к. в кеш не попали js функции из самого виджета, а только  html.

Пробовал вызывать виджет через renderDynamic
http://www.yiiframework.com/doc-2.0/yii-base-view.html#renderDynamic%28%29-detail
Результата все равно не получил.

Подскажите, как можно исключить виджет из кеширования?

**Comment by webadmin87** [comment]
Сходу вижу два варианта решения проблемы:
1. Принудительно подключать ассеты виджета в контроллере, в случае если данные берутся из кеша.
2. Кешировать данные по другому, используя fragment caching. http://www.yiiframework.com/doc-2.0/guide-caching-fragment.html

**Comment by loveorigami** [comment]
Спасибо. тоже так предположил.
